### ISSUE TITLE
Not compatible with Botkit 4

### ISSUE THREAD

**Issue by kvarela** [howdyai/botkit-storage-redis#15]
I've tried to use this with Botkit 4, but it fails with error like this:
```
Experienced an error inside the turn handler TypeError: this.storage.read is not a function
    at Promise.resolve.then (/Users/home/swirl/swirl-app/node_modules/botbuilder-core/src/botState.ts:87:37)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:43349) UnhandledPromiseRejectionWarning: TypeError: this.storage.read is not a function
    at Promise.resolve.then (/Users/home/swirl/swirl-app/node_modules/botbuilder-core/src/botState.ts:87:37)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

is this to be expected? Any plans to update this library?

**Comment by bfoura** [comment]
I think that you used this [library](https://github.com/howdyai/botkit-storage-redis), and its no longer maintained, or at least not compatible with BotKit 4 interfaces
